export abstract class StreamGraphServiceAbstract {
  public abstract getColors = (): string[] => [];
  public abstract getCategories = (): string[] => [];
  public getFinladData = (): number[] => [];
  public getAustriaData = (): number[] => [];
  public getSweedenData = (): number[] => [];
  public getUnitedStatesData = (): number[] => [];
  public getNorwayData = (): number[] => [];
  public getEastGermanyData = (): number[] => [];
  public getWestGermanyData = (): number[] => [];
  public getGermanyData = (): number[] => [];
  public getNetherlandsData = (): number[] => [];
  public getItalyData = (): number[] => [];
  public getCanadaData = (): number[] => [];
  public getSwitzerlandData = (): number[] => [];
  public getGreatBritianData = (): number[] => [];
  public getFranceData = (): number[] => [];
  public getHungaryData = (): number[] => [];
  public getChinaData = (): number[] => [];
  public getSouthKoreaData = (): number[] => [];
  public getLatviaData = (): number[] => [];
  public getRussiaData = (): number[] => [];
  public getJapanData = (): number[] => [];
  public getPolandData = (): number[] => [];
  public getSpainData = (): number[] => [];
  public getBerlarusData = (): number[] => [];
  public getKazakhstamData = (): number[] => [];
  public getDenmarkData = (): number[] => [];
  public getUkraineData = (): number[] => [];
  public getRomaniaData = (): number[] => [];
  public getLiechtensteinData = (): number[] => [];
  public getUnifiedTeamData = (): number[] => [];
}
